---
abstract: "Calculate Dice's coefficient of two strings"
author:
  - 'gray <gray@cpan.org>'
build_requires:
  Test::More: 0.98
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-Dice
no_index:
  directory:
    - t
    - inc
requires:
  parent: 0
resources:
  repository: https://github.com/gray/text-dice
version: 0.02
